config/routes.rb
Rails.application.routes.draw do

  root 'applicants#index'

  get 'skills/search' => 'skills#search'

  resources :applicants do
    member do
      get 'suitable_vacancies'
    end
  end

  resources :vacancies do
    member do
      get 'suitable_applicants'
    end
  end

end

app/models/applicant.rb
# == Schema Information
#
# Table name: applicants
#
#  id              :integer          not null, primary key
#  full_name       :string           not null
#  contact_info    :string           not null
#  status          :integer          not null
#  expected_salary :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Applicant < ActiveRecord::Base
  has_many :applicant_skills, dependent: :delete_all
  has_many :skills, through: :applicant_skills

  enum status: [:active, :idle]

  before_save :strip_spaces_from_name

  # presence is validated implicitly with the regex
  validates :full_name, format: { with: /\A\s*(\p{Cyrillic}+\s+){2}\p{Cyrillic}+\s*\z/,
                                          message: "3 слова, только кириллические символы и пробелы" }

  validate :contact_info_email_or_phone

  scope :with_skills, ->(skill_names = nil) do
    if skill_names.blank? || !skill_names.kind_of?(Array)
      all
    else
      joins(:skills).where(skills: {name: skill_names}).uniq
    end
  end

  scope :active, -> {where(status: Applicant.statuses[:active])}

  def strip_spaces_from_name
    self.full_name = full_name.gsub(/\s{2,}/, ' ').strip if attribute_present?(:full_name)
  end

  def contact_info_email_or_phone
    unless self.contact_info =~ /\A[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,8}\z/ || #email regex
           self.contact_info =~ /\A\+[0-9]{11}\z/ # phone number in the format +71234567890
      errors.add(:contact_info, "некорректный формат телефона или емейла")
    end
  end

  def skill_list
    self.skills.map(&:name).join(',')
  end

  def skill_list=(string)
    string.split(',').each do |s|
      skill = Skill.find_or_create_by(name: s)
      self.applicant_skills.find_or_initialize_by(skill_id: skill.id)
    end
  end

end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update, :destroy, :suitable_vacancies]

  # GET /applicants
  # GET /applicants.json
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to @applicant, notice: 'Applicant was successfully created.' }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1
  # PATCH/PUT /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1
  # DELETE /applicants/1.json
  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to applicants_url, notice: 'Applicant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def suitable_vacancies
    skills = @applicant.skills.map(&:name)
    vacancies = Vacancy.not_expired.with_skills(skills).order('salary DESC')
    full_match = vacancies.select{|v| (v.skills.map(&:name) - skills).empty? }
    partial_match = vacancies.reject{|v| (v.skills.map(&:name) - skills).empty? }
    @vacancies = if full_match.size > partial_match.size
                   full_match.zip(partial_match).flatten
                 else
                   partial_match.zip(full_match).map(&:reverse).flatten
                 end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_params
      params.require(:applicant).permit!
    end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/applicants/_form.html.slim
= form_for @applicant, html: { class: "form form-horizontal applicant" } do |f|
  .form-group
    = f.label :full_name, :class => 'control-label'
    .controls
      = f.text_field :full_name, :class => 'form-control', placeholder: "Иванов Иван Иванович (3 слова, только кириллические буквы)"
    = error_span(@applicant[:full_name])
  .form-group
    = f.label :contact_info, :class => 'control-label'
    .controls
      = f.text_field :contact_info, :class => 'form-control', placeholder: "адрес эл-почты или номер телефона в формате +71234567890"
    = error_span(@applicant[:contact_info])
  .form-group
    = f.label :status, :class => 'control-label'
    .controls
      = f.select :status, options_for_select([['Активен', :active], ['Не ищет', :idle]]), {}, {class: 'form-control'}
    = error_span(@applicant[:status])
  .form-group
    = f.label :expected_salary, :class => 'control-label'
    .controls
      = f.number_field :expected_salary, :class => 'form-control'
    = error_span(@applicant[:expected_salary])
  .form-group
    = f.label :skills, :class => 'control-label'
    .controls
      = f.text_field :skill_list, class: 'form-control skills'

  = f.submit 'Сохранить', :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), applicants_path, :class => 'btn'
  '
  = link_to 'Найти вакансии', suitable_vacancies_applicant_path(@applicant), :class => 'btn'

app/views/applicants/edit.html.slim
- model_class = Applicant
div class="page-header"
  h1 Редактировать работника
= render :partial => "form"

app/views/applicants/index.html.slim
- model_class = Applicant
div class="page-header"
  h1 Работники
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:full_name)
      th= model_class.human_attribute_name(:contact_info)
      th= model_class.human_attribute_name(:status)
      th= model_class.human_attribute_name(:expected_salary)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @applicants.each do |applicant|
      tr
        td= link_to applicant.full_name, applicant_path(applicant)
        td= applicant.contact_info
        td= t "applicant_status.#{applicant.status}"
        td= applicant.expected_salary
        td= applicant.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_applicant_path(applicant), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), applicant_path(applicant), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
          '
          = link_to 'Найти вакансии', suitable_vacancies_applicant_path(applicant), :class => 'btn btn-default btn-xs'

= link_to t('.new', :default => t("helpers.links.new")), new_applicant_path, :class => 'btn btn-primary'

app/views/applicants/new.html.slim
- model_class = Applicant
div class="page-header"
  h1 Создать работника
= render :partial => "form"

app/views/applicants/show.html.slim
- model_class = Applicant
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:full_name) + ':'
  br
  = @applicant.full_name
p
  strong= model_class.human_attribute_name(:contact_info) + ':'
  br
  = @applicant.contact_info
p
  strong= model_class.human_attribute_name(:status) + ':'
  br
  = t "applicant_status.#{@applicant.status}"
p
  strong= model_class.human_attribute_name(:expected_salary) + ':'
  br
  = @applicant.expected_salary
p
  strong Навыки:
  br
  =text_field_tag :skill_list, @applicant.skills.map(&:name).join(','), class: 'skills skills-disabled'

= link_to t('.back', :default => t("helpers.links.back")), applicants_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_applicant_path(@applicant), :class => 'btn btn-default'
'
= link_to 'Найти вакансии', suitable_vacancies_applicant_path(@applicant), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), applicant_path(@applicant), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/applicants/suitable_vacancies.html.slim
div class="page-header"
  h1=@applicant.full_name
  h2 Подходящие вакансии

table class="table table-striped"
  thead
    tr
      th Полностью подходят
      th Частично подходят
  tbody
    - @vacancies.each_slice(2) do |v|
      tr
        / full match
        td= link_to "#{v[0].title} (#{v[0].salary})", vacancy_path(v[0]) if v[0]
        /partial match
        td= link_to "#{v[1].title} (#{v[1].salary})", vacancy_path(v[1]) if v[1]