config/routes.rb
Rails.application.routes.draw do

  root 'applicants#index'

  get 'skills/search' => 'skills#search'

  resources :applicants do
    member do
      get 'suitable_vacancies'
    end
  end

  resources :vacancies do
    member do
      get 'suitable_applicants'
    end
  end

end

app/models/vacancy.rb
# == Schema Information
#
# Table name: vacancies
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  valid_to     :datetime         not null
#  salary       :integer
#  contact_info :text             not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Vacancy < ActiveRecord::Base
  has_many :vacancy_skills, dependent: :delete_all
  has_many :skills, through: :vacancy_skills

  scope :with_skills, ->(skill_names = nil) do
    if skill_names.blank? || !skill_names.kind_of?(Array)
      all
    else
      joins(:skills).where(skills: {name: skill_names}).uniq
    end
  end

  scope :not_expired, -> {where('valid_to > ?', Date.today)}

  def skill_list
    self.skills.map(&:name).join(',')
  end

  def skill_list=(string)
    string.split(',').each do |s|
      skill = Skill.find_or_create_by(name: s)
      self.vacancy_skills.find_or_initialize_by(skill_id: skill.id)
    end
  end

end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: [:show, :edit, :update, :destroy, :suitable_applicants]

  # GET /vacancies
  # GET /vacancies.json
  def index
    @vacancies = Vacancy.all
  end

  # GET /vacancies/1
  # GET /vacancies/1.json
  def show
  end

  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new
  end

  # GET /vacancies/1/edit
  def edit
  end

  # POST /vacancies
  # POST /vacancies.json
  def create
    @vacancy = Vacancy.new(vacancy_params)

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully created.' }
        format.json { render :show, status: :created, location: @vacancy }
      else
        format.html { render :new }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacancies/1
  # PATCH/PUT /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacancy }
      else
        format.html { render :edit }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1
  # DELETE /vacancies/1.json
  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html { redirect_to vacancies_url, notice: 'Vacancy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def suitable_applicants
    skills = @vacancy.skills.map(&:name)
    p skills
    applicants = Applicant.active.with_skills(skills).order('expected_salary ASC')
    p applicants
    full_match = applicants.select{|v| (v.skills.map(&:name) - skills).empty? }
    partial_match = applicants.reject{|v| (v.skills.map(&:name) - skills).empty? }
    @applicants = if full_match.size > partial_match.size
                   full_match.zip(partial_match).flatten
                 else
                   partial_match.zip(full_match).map(&:reverse).flatten
                 end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacancy_params
      params.require(:vacancy).permit!
    end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/vacancies/_form.html.slim
= form_for @vacancy, html: { class: "form form-horizontal vacancy" } do |f|
  .form-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'form-control'
    = error_span(@vacancy[:title])
  .form-group
    = f.label :valid_to, :class => 'control-label'
    .controls
      = f.date_field :valid_to, min: Date.today, :class => 'form-control'
    = error_span(@vacancy[:valid_to])
  .form-group
    = f.label :salary, :class => 'control-label'
    .controls
      = f.text_field :salary, :class => 'form-control'
    = error_span(@vacancy[:salary])
  .form-group
    = f.label :contact_info, :class => 'control-label'
    .controls
      = f.text_field :contact_info, :class => 'form-control'
    = error_span(@vacancy[:contact_info])
  .form-group
    = f.label :skills, :class => 'control-label'
    .controls
      = f.text_field :skill_list, class: 'form-control skills'
  = f.submit 'Сохранить', :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), vacancies_path, :class => 'btn'
  '
  = link_to 'Найти вакансии', suitable_applicants_vacancy_path(@vacancy), :class => 'btn'

app/views/vacancies/edit.html.slim
- model_class = Vacancy
div class="page-header"
  h1 Редактировать вакансию
= render :partial => "form"

app/views/vacancies/index.html.slim
- model_class = Vacancy
div class="page-header"
  h1 Вакансии
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:valid_to)
      th= model_class.human_attribute_name(:salary)
      th= model_class.human_attribute_name(:contact_info)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @vacancies.each do |vacancy|
      tr
        td= link_to vacancy.title, vacancy_path(vacancy)
        td= vacancy.valid_to
        td= vacancy.salary
        td= vacancy.contact_info
        td= vacancy.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_vacancy_path(vacancy), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), vacancy_path(vacancy), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
          '
          = link_to 'Найти работников', suitable_applicants_vacancy_path(vacancy), :class => 'btn btn-default btn-xs'

= link_to t('.new', :default => t("helpers.links.new")), new_vacancy_path, :class => 'btn btn-primary'

app/views/vacancies/new.html.slim
- model_class = Vacancy
div class="page-header"
  h1 Создать вакансию
= render :partial => "form"

app/views/vacancies/show.html.slim
- model_class = Vacancy
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:title) + ':'
  br
  = @vacancy.title
p
  strong= model_class.human_attribute_name(:valid_to) + ':'
  br
  = @vacancy.valid_to
p
  strong= model_class.human_attribute_name(:salary) + ':'
  br
  = @vacancy.salary
p
  strong= model_class.human_attribute_name(:contact_info) + ':'
  br
  = @vacancy.contact_info
p
  strong Навыки:
  br
  =text_field_tag :skill_list, @vacancy.skills.map(&:name).join(','), class: 'skills skills-disabled'

= link_to t('.back', :default => t("helpers.links.back")), vacancies_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_vacancy_path(@vacancy), :class => 'btn btn-default'
'
= link_to 'Найти работников', suitable_applicants_vacancy_path(@vacancy), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), vacancy_path(@vacancy), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/vacancies/suitable_applicants.html.slim
div class="page-header"
  h1=@vacancy.title
  h2 Подходящие работники

table class="table table-striped"
  thead
    tr
      th Полностью подходят
      th Частично подходят
  tbody
    - @applicants.each_slice(2) do |v|
      tr
        / full match
        td= link_to "#{v[0].full_name} (#{v[0].expected_salary})", applicant_path(v[0]) if v[0]
        /partial match
        td= link_to "#{v[1].full_name} (#{v[1].expected_salary})", applicant_path(v[1]) if v[1]